
# This is a template Makefile generated by rpcgen

# Parameters

SERVER = rpc_servidor
CLIENT = servidor

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = PrintService.x

TARGETS_SVC.c = PrintService_svc.c PrintService_server.c
TARGETS_CLNT.c = PrintService_clnt.c PrintService_client.c libserver.c comm.c servidor.c
TARGETS = comm.h rpc_funciones.h libserver.h servidor.h PrintService_clnt.c PrintService_svc.c servidor.c PrintService_server.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CPPFLAGS += -D_REENTRANT
CFLAGS += -g -I/usr/include/tirpc -fPIC
LDLIBS += -lnsl -lpthread -ldl -ltirpc -lpthread
RPCGENFLAGS =

# Targets 

all : libserver.so $(CLIENT) $(SERVER)

libserver.so: $(OBJECTS_CLNT)
	$(CC) -shared  $(CPPFLAGS) $(CFLAGS) $^ -o libserver.so

$(CLIENT): servidor.o libserver.so
	$(CC) $(CPPFLAGS) $(LDFLAGS) $^ $(LDLIBS) -o $@ -L. -lserver

$(TARGETS) : $(SOURCES.x)
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)


$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c)

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c)

$(SERVER) : $(OBJECTS_SVC)
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

%.o: %.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

 clean:
	 $(RM) core $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER) cliente.o libserver.so