/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "PrintService.h"
#include "rpc_funciones.h"

int printService_1(char *stringToPrint)
{
    char *host = getenv("IP_TUPLAS");
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;

	clnt = clnt_create (host, PRINTSERVICE, PRINTSERVICEVER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	retval_1 = rpc_displayvalues_1(stringToPrint, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
    clnt_destroy(clnt);
    return result_1;

}

